name: Release
on:
  release:
    types: [published]
jobs:
  release:
    runs-on: ubicloud
    steps:
    - name: Checkout
      uses: actions/checkout@e2f20e631ae6d7dd3b768f56a5d2af784dd54791 # v2.5.0

    - name: Set up Python
      uses: actions/setup-python@13ae5bb136fac2878aff31522b9efb785519f984 # v4.3.0
      with:
        python-version: '3.10.10'

    - name: Install and configure Poetry
      run: |
        cd python
        curl -sSL https://install.python-poetry.org | python3 -
      env:
        POETRY_VERSION: 1.4.2

    - name: Build
      run: poetry build
      working-directory: python

    - name: Publish
      run: poetry publish --username=__token__ --password=${{ secrets.PYPI_TOKEN }}
      working-directory: python
